CREATE TABLE [ELT].[IngestDefinition]
(
	[IngestID] int not null identity,
	[SourceSystemName] varchar(50) not null,
	[StreamName] varchar(100) null,
	[SourceSystemDescription] varchar(200) null,
	[Backend] varchar(30) null,
	[DataFormat] varchar(10) null,
	[EntityName] varchar(100) null,
	[DeltaName] varchar(50) null,
	[DeltaFormat] varchar(30) null,
	[LastDeltaDate] datetime2 null,
	[LastDeltaNumber] int null,
	[LastDeltaString] varchar(50) null,
	[MaxIntervalMinutes] int null,
	[MaxIntervalNumber] int null,
	[DataMapping] varchar(max) null,
	[SourceFileDropFileSystem] varchar(50) null,
	[SourceFileDropFolder] varchar(200) null,
	[SourceFileDropFile] varchar(200) null,
	[SourceFileDelimiter] char(1) null, 
	[SourceFileHeaderFlag] bit null,
	[SourceStructure] varchar(max) null,
	[DestinationRawFileSystem] varchar(50) null,
	[DestinationRawFolder] varchar(200) null,
	[DestinationRawFile] varchar(200) null,
	[RunSequence] int null,
	[MaxRetries] int null,
	[ActiveFlag] bit not null,
	[L1TransformationReqdFlag] bit not null,
	[L2TransformationReqdFlag] bit not null,
	[DelayL1TransformationFlag] bit not null,
	[DelayL2TransformationFlag] bit not null,
	[CreatedBy] nvarchar(128) not null,
	[CreatedTimestamp] datetime not null,
	[ModifiedBy] nvarchar(128) null,
	[ModifiedTimestamp] datetime null,
)

